### ISSUE TITLE
The pages proofed graphs take a long time if data is not cached

### ISSUE THREAD

**Issue by srjfoo** [DistributedProofreaders/dproofreaders#1025]
In recent experimentation, `stats/pages_proofed_graphs.php` for all rounds on the production site take over 70 seconds if there isn't a recent cache of the data. Is there a way to improve performance (or cause it to have less impact on users viewing the graphs)? When it takes that long for a page to display, it gets worrisome.

I assume that the culprit is the cumulative graph on each page, and this will likely only to continue to get worse.

**Comment by cpeel** [comment]
We should start by caching the graphs until the next server-time midnight, that way we only incur one slow-load a day. I don't think any of those graphs are important enough to retain current-day data.

I'm dubious if we can do anything about the long generation time without changing what's in the charts -- it's just a lot of data.

**Comment by srjfoo** [comment]
> We should start by caching the graphs until the next server-time midnight, that way we only incur one slow-load a day. I don't think any of those graphs are important enough to retain current-day data.

I can't say for sure, because I'm not adept at reading that part of the code, but I don't think current day data is used, anyway. Looking (for example) at P1's "Pages Done Per Day (Jan 2024)" and "Cumulative Pages Done (Jan 2024)", the last bar on each of those graphs is current-day-minus-one. 

> I'm dubious if we can do anything about the long generation time without changing what's in the charts -- it's just a lot of data.

Yeah. The only idea I've had for the last two graphs on the page is to store the data and make those static graphs that can be refreshed once a month, maybe. But I don't have any idea whether that would be workable or not.

**Comment by cpeel** [comment]
#1033 should mitigate this. Let's see how the page perf feels after we get this deployed.

**Comment by cpeel** [comment]
#1033 seems to make the page feel snappy for most use-cases so I'm going to close this issue.
