### ISSUE TITLE
Fix oddness in "Pages Done Per Day" graphs

### ISSUE THREAD

**Issue by jmdyck** [DistributedProofreaders/dproofreaders#1198]
See the discussion in https://github.com/DistributedProofreaders/dproofreaders/pull/1196#issuecomment-2081583882 + following.

The problems show up when we plot a bar chart and a superimposed line-graph. I think this is just the "Pages Proofread" graphs, where the line-graphs are "21-day SMA" and "Goal". Moreover, it's only noticeable when the bars have an appreciable width, so it's just the "Pages Done Per Day" graphs for the current and previous months.

The problems are:
- For a given day, the day-label, the x-axis tick, and the bar are all center-aligned, but the points for the SMA and Goal are plotted a half-day-width to the left (i.e., at the left edge of the bar). (For SMA, this is particularly odd, because it seems like the effect of that day's proofing on the SMA happens *before* that day.)

- There's no line segment representing the change in SMA between the last day of the previous month and the first of this month. (In our current graphs, this segment would cross the bar for the last day of the previous month, but it isn't plotted.)

**Comment by cpeel** [comment]
Thanks for filing this Michael. I'm most interested in solving the first bullet. The second one would be nice to have but I could see it being more complicated and if we punt it we punt it.

@chrismiceli - this isn't at all urgent but you have the most expertise with the current graphing code.

**Comment by chrismiceli** [comment]
I will look into this and let you know if I can figure out why there is an offset.

**Comment by cpeel** [comment]
#1200 fixed the line alignment issue.

I'm going to WONTFIX the "SMA should go beyond the days on the graph" because while it would be nice it's not really important in the grand scheme of things and I suspect the issue will just get send into defergatory.
