### ISSUE TITLE
Delete XML project feeds

### ISSUE THREAD

**Issue by cpeel** [DistributedProofreaders/dproofreaders#1224]
The project XML feeds are no longer valuable and haven't been for years. An analysis of the feed requests from pgdp.net show that the RSS feeds are used frequently but only bots and crawlers are accessing the XML feeds.

We should:
* remove the XML-based code from [backend.php](https://github.com/DistributedProofreaders/dproofreaders/blob/master/feeds/backend.php) and make it only return RSS regardless of what `type` is passed in (if any).
* update appropriate pages that link to the XML-based project feeds.
* delete the [rss](https://github.com/DistributedProofreaders/dproofreaders/blob/master/graphics/rss.gif) image and use the [rss-square](https://fontawesome.com/v5/search?q=rss-square&o=r&m=free) FontAwesome icon.
* ideally do some cleanup in `backend.php` along the way.

We need to confirm that we do not break existing RSS links for the feeds.

The team and member XML feeds have been accessed non-zero times in the past month (7 and 38 respectively) and while my inclination is to delete them we should do that in a separate PR if we decide to do so.

**Comment by mrducky4** [comment]
I'm interested in working on this issue.

**Comment by cpeel** [comment]
> I'm interested in working on this issue.

@mrducky4 - sounds great!

One thing I thought of is that caching the feed in a file and serving it up from there is probably no longer necessary for our current database and production server. Moreover we now have a memcached instance for hot data that we could use via the [memoize()](https://github.com/DistributedProofreaders/dproofreaders/blob/master/pinc/misc.inc#L1447) function if we wanted to cache it.

**Comment by cpeel** [comment]
Fixed by #1269 by @mrducky4  -- thanks Mark!
