### ISSUE TITLE
Convert system/exec usages to Symfony's Process class

### ISSUE THREAD

**Issue by cpeel** [DistributedProofreaders/dproofreaders#1274]
Replace all applicable uses of [exec](https://secure.php.net/manual/en/function.exec.php), [passthru](https://secure.php.net/manual/en/function.passthru.php), [shell_exec](https://secure.php.net/manual/en/function.shell-exec.php) and [system](https://secure.php.net/manual/en/function.system.php) with Symfony's [Process](https://symfony.com/doc/5.x/components/process.html) class. The package/class was introduced into the codebase in https://github.com/DistributedProofreaders/dproofreaders/pull/1273

Add a CI script that checks these functions aren't used in the code with an approve-list for files we've allowed as an exceptions. Since this is security related, we might change `check_security.sh` into a PHP file similar to `check_includes.php` and put it in there but other approaches are fine.

**Comment by cpeel** [comment]
Note: iterative work on this issue is appreciated, it doesn't need to be solved all at once.

**Comment by mrducky4** [comment]
I will start working on this.
