### ISSUE TITLE
Remove frameset from PM WordCheck tools

### ISSUE THREAD

**Issue by cpeel** [DistributedProofreaders/dproofreaders#562]
Three of the PM WordCheck tools use framesets:
* `tools/project_manager/show_word_context.php`
* `tools/project_manager/show_all_good_word_suggestions.php`
* `tools/project_manager/show_good_word_suggestions_detail.php`

These need to be updated to use the new `scripts/splitControl.js` instead.

**Comment by chrismiceli** [comment]
Should we close this not that it is merged, or wait until deployed? Not sure our process for github issues.

**Comment by cpeel** [comment]
This ticket is for 3 different PM WordCheck interfaces and our MR was just for one of them, right?

**Comment by chrismiceli** [comment]
Ah yes.

**Comment by cpeel** [comment]
The merge of the `page_browser_uses_api` branch resolved this issue.
