### ISSUE TITLE
Incorrect validation of email domain name during user registration

### ISSUE THREAD

**Issue by wf49670** [DistributedProofreaders/dproofreaders#732]
pinc/email_address.inc includes this line which only allows email domain names that are between 2 and 4 characters in length:
`$domain_re = "($label_re\.)+[A-Za-z]{2,4}";`

A recently registered user pointed out that there are now domain names, like the one she works for, which are longer. Example: samvid.ventures, so we should adjust that validation step.

**Comment by cpeel** [comment]
According [to this](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_domain_name) the maximum length of a TLD is 63 characters.

FYI: [here's the list of all current TLDs](https://data.iana.org/TLD/tlds-alpha-by-domain.txt), not that I think we should try to validate against it.
