### ISSUE TITLE
Integrate misc_user_stats.php into the site code

### ISSUE THREAD

**Issue by cpeel** [DistributedProofreaders/dproofreaders#757]
`stats/misc_user_stats.php` is not linked anywhere within the site code. We should figure out if these graphs should be moved to a different page or if this page should merely be linked from the main stats page, but it should be reachable via a link somewhere.

**Comment by chrismiceli** [comment]
I think it is ok to add it to the stats overview page and almost suggested it during migration. @lhamilton1 probably has an opinion. For reference, this is the page: https://www.pgdp.net/c/stats/misc_user_stats.php

**Comment by lhamilton1** [comment]
I'm fine with having a link. They're too nice to hide.
