### ISSUE TITLE
Remove `smooth` directory when a project is archived.

### ISSUE THREAD

**Issue by srjfoo** [DistributedProofreaders/dproofreaders#773]
While a project is available for smooth reading, the `smooth` directory contains all of the files that are availble for separate download or online viewing. Once the project leaves the SR pool, though, it's unnecessary to keep the `smooth`: it takes up unnecessary disk space, because the original upload from the PPer is still available as a zip file in the project directory.

It's probably easiest to do this when a project is archived.

**Comment by cpeel** [comment]
Fixed in https://github.com/DistributedProofreaders/dproofreaders/pull/787
